export enum SeederEnum {
  CRM_ACCOUNTS = 'CRM_ACCOUNTS',
  CRM_LOCATIONS = 'CRM_LOCATIONS',
  MIGRATIONS = 'MIGRATIONS',
  OC_NCE = 'OC_NCE',
  ROLE_PERMISSIONS = 'ROLE_PERMISSIONS',
  SESSIONS_FILTERS = 'SESSIONS_FILTERS',
  STAFFING_MANAGEMENT_STAFF_LIST_FILTERS = 'STAFFING_MANAGEMENT_STAFF_LIST_FILTERS',
}
